#!/usr/bin/env python

from livereload.task import Task
from livereload.compiler import shell

Task.add('sass/*.scss', shell('compass compile'))
Task.add('index.jade', shell('jade index.jade'))
Task.add('javascripts/app.py', shell('./mkapp.sh'))
